version: '3.0'

services:
  main:
    container_name: main
    build:
      context: .
    env_file:
      - .dev.env
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - 3000:3000
      - 8080:8080
    command: npm run start:dev
    depends_on:
      - mongo
      - redis
    restart: always
  mongo:
    container_name: mongo
    image: mongo:6.0
    ports:
      - 27017:27017
    volumes:
      - mongodb:/data/db
    restart: always
  redis:
    container_name: cache
    image: redis
    ports:
      - 6379:6379
    volumes:
      - redis:/data
volumes:
  mongodb:
  redis:
    driver: local
